### ISSUE TITLE
Opening up customizable APIs such as adding a custom selector.

### ISSUE THREAD

**Issue by dylanwijnen1** [mikke89/RmlUi#175]
Hey there,

First of I have to say this is an amazing project. And I'm very new to the project.

I wanted to add functionality for adding a placeholder attribute onto input[type="text"] and so far with a custom plugin I've been able to get quite far in that regards. But I noticed that the functionality for adding a new pseudo-selector is currently in a private scope. See: [`StyleSheetFactory::selectors`](https://github.com/mikke89/RmlUi/blob/master/Source/Core/StyleSheetFactory.h#L81)

I don't know if this is something being worked on for Rml 4.0 but I thought I'd ask if there were any plans in opening up the API of the framework to allow for more plugin flexibility/extensibility. All I noticed is that there's a lot of work being done in refactoring a bunch of systems.

Thanks!

**Comment by mikke89** [comment]
Hi, welcome, and thanks for your kind words!

It is already possible to add pseudo classes to any element, and write selectors based on that. I wonder if this perhaps is what you need in this case? The code you point to is for structural pseudo classes (eg. nth-child and so on).

More generally, we don't have any specific plans in terms of adding more customization points. There are tradeoffs for doing this, and generally I will say we need to consider if it makes sense for each specific case.

- First of all, I'd say we already have a very large surface area for customization and hooking into the library.
- Secondly, the project is open source, so if you need something very specific, it is always possible to modify the library directly.
- Third, for things such as new structural selectors, I'd rather see PRs submitted so that everyone can enjoy the improvements without the need to add or create plugins.
- Last, and perhaps most importantly, adding more points of customization creates more friction when we want to add new features, need to refactor, or improve performance. We need to take care not to break API (at least not too often), and this can easily become more costly in the future than one might anticipate.

Hope this makes sense, and remember that PRs are very much welcome if you think they can help others too ;)

**Comment by dylanwijnen1** [comment]
Hey Mike,

Thanks for letting me know. My initial thought of implementing the placeholder text was to create another text element onto the input. But I realize I could as well just reuse the text element and add the pseudo class when the input is blank. Hence I asked about the structural pseudo classes.

Thanks for clarifying the ideals of the project and it makes perfect sense. I'm also not well versed with Github PR's but when I do have an interesting feature I can see everyone benefiting from I would totally look into that.

Keep up the great work. I'm looking forward to RmlUi 4.0!
