### ISSUE TITLE
Setting attributes that would imply attaching event listeners

### ISSUE THREAD

**Issue by ZombieRaccoon** [mikke89/RmlUi#188]
Hello,

I've recently encountered a potential issue where setting element attributes (eg. "onclick") that would imply attaching event listeners are meaningless when done so using the C++ API. The particular case I'm after involves Lua, as I'll explain below.

Consider the following minimal example:
```
<rml>
    <head>
        <style>
            body
            {
                font-family: Arial;
            }
        </style>
    </head>
    <body>
        <button onclick="print('hello')">Hello</button>
    </body>
</rml>
```

When clicking the button the Lua event listener is triggered and the message eventually reaches Rml::SystemInterface::LogMessage.

Consider the following minimal C++ excerpt that uses the ```hello.rml``` introduced before, only this time without the predefined button:
```
document = context->LoadDocument("hello.rml");
auto* button = document->AppendChild(document->CreateElement("button"));
button->SetAttribute("onclick", "print('hello')");
button->SetInnerRML("hello");
```

Unfortunately, nothing happens when the button is clicked.

I've put some effort into debugging the phenomenon in hopes of stumbling upon an error of my own, but I kind of settled on the theory that the Lua plugin is currently incapable of handling such a use case.

Can you confirm this? If so, would you consider implementing this feature?

**Comment by mikke89** [comment]
Hi and yes, I can confirm this behavior. The `on...` attributes are only applied with attributes initially set on the element, this is not particularly tied to the Lua plugin.

As a workaround, you can call `Factory::InstanceElement` and pass in the attributes during construction there. Does that work for you?

Let me just describe the issue we are dealing with here in some more detail. While it would be easy to hook up the event every time we change an `on...` attribute, I think the main reason this isn't being done right now is that there is currently no easy way to remove the particular `on...` attribute if we are overwriting an existing one. Say we set `onclick` twice, now we have two click events bound to the element. While this could certainly be solved, it would take some effort. There are other related improvements that would be nice with events, in particular event listener ownership, so it would be naturally to do this as part of a bigger review, but right now this is not a big priority. Especially if that workaround works for you. What are your thoughts on this?

**Comment by ZombieRaccoon** [comment]
First of all, thanks for the workaround! It's but a minor inconvenience.

My thoughts on this must be taken with a grain of salt, since I merely got a sneak peek at certain parts of the codebase while debugging and performing static analysis, but the on the whole it's naturally quite unknown to me. 

I noticed that upon element instantiation using ```Rml::Factory::InstanceElement``` the magic actually happens in ```ElementUtilities::BindEventAttributes```, which eventually invokes an ```Rml::EventListenerInstancer``` implementation - ```Rml::Lua::LuaEventListenerInstancer``` in my case - which ends the story on a positive note. Moving on, when setting an attribute using ```Element::SetAttribute``` one's eye is immediately drawn to ```Element::OnAttributeChange```, where the same thing could be done - albeit with the caveats you pointed out. I see the problem you mentioned regarding replacement in that the ```Rml::EventListener``` implementations attached to elements neither carry information as to their origins, nor are stored in such a manner, either of which would certainly be crucial when dealing with the replacement or removal of such attributes.

Having said all of that, to make the connection between attribute and event listener it would be best if this information resided in ```Rml::Element```, in my opinion. Would you agree? This however, doesn't universally address event listener ownership, which might as well be an entirely new concept. Would you please explain a little more broadly as to what this means for you?

Finally, I can understand that making this work isn't of the highest priority, but if something resembling a design emerges out of the discussion then perhaps we or even someone else can pick it up later and make a contribution based on it.

**Comment by mikke89** [comment]
Sounds like you have a pretty good grasp on the code structure already! You have pretty much detailed my thoughts exactly.

I think a natural place to put the origin is in the `EventListenerEntry` in `EventDispatcher.h`. There should only be one of a given listener originating from attributes for a given event id. Actually, your original issue could probably be solved without too much trouble by adding such an origin.

As to the ownership issue. This is something that has irked me for a while but I haven't really thought through a good solution. To illustrate the problem, take a look at the `invaders` sample. In the sample's `EventInstancer.cpp` a new event listener is constructed (here confusingly called Event), however, it's destruction happens entirely separate, in `Event.cpp` where it deletes itself. The ownership is initially passed using just a raw pointer and eventually ends up on the element's list of event listeners. This list has no indication of ownership or lifetimes, some event listeners manage their lifetime by destroying themselves, others are managed entirely separate, sometimes in user land. It's not an uncommon issue that an object therein has already been destroyed, typically in user code space, but still referenced - eventually leading to a crash. 

Now I haven't really thought through a good solution, but I don't really like that whole situation. Another related note, I've also wanted to see if collecting all the events into a single document object could speed things up. Ie. right now all dispatched events are iterated through all the target's ancestors twice. There's not a whole lot of point in doing this if there are no listeners in those elements, so a more centralized coordinator could be beneficial in terms of performance.

With that said, I don't think it's a huge issue all in all, and the event system shouldn't be a big performance issue except for rare situations. I feel there are more important things to work on right now in the library, rather than a big rewrite of the event system.

**Comment by ZombieRaccoon** [comment]
I agreed with your proposal to put it in ```EventListenerEntry``` so much so that I implemented it in #189.

Moving on to the ownership issue: such separation of construction and destruction coupled with the ambiguity regarding ownership rarely leads to anything but chaos, so I completely agree that there must be improvement in that department.

I believe that the best way to tackle the question of explicit ownership in modern C++ is by using smart pointers. In my opinion, as an instancer itself is a clean manifestation of the abstract factory pattern, it would be best if it determined the ownership of its creations by using a certain type of smart pointer - depending on the usage patterns of these event listeners. If it's desirable for an event listener to be attached to multiple dispatchers, then I'd simply go with ```std::shared_ptr``` and ```std::unique_ptr``` otherwise. In my mind, this should be a more or less straightforward change that would iron out any questionable parts; albeit at the cost of breaking the interface as part of this simple modernization.

As for the centralized event dispatchment, I'd say that's a topic for another day when based on measurements one concludes that the current architecture is unbearable as a motivation for such a larger-scale change.

**Comment by mikke89** [comment]
Thanks, PRs are very much appreciated!

Yeah, one of the first things I did with this library was to use smart pointers for ownership. EventListeners proved to be tricky though, because sometimes their lifetimes are tied to the owning `EventDispatcher`, but other times lifetimes are entirely controlled in the user space often outliving the event dispatcher. Thus, we can't simply replace the raw pointers with `unique_ptr`s.

I think a more modern approach would be to take `std::functions` and let users do their callbacks in lambda functions. However, this would be a major breaking change for pretty much everyone so that is not done lightly. Any major change also need to see how they impact performance first.

Totally agree on the centralized dispatchment.

**Comment by ZombieRaccoon** [comment]
I understand and I do agree that the true way out is ```std::function```. By the way, I'd say that the new data binding feature is done really well in that regard!

**Comment by ZombieRaccoon** [comment]
I'll close the issue since #189 fulfills everything I outlined in the original description. Thanks for the discussion!

**Comment by mikke89** [comment]
Thanks, I appreciate the discussion :)
