### ISSUE TITLE
inline svg

### ISSUE THREAD

**Issue by actondev** [mikke89/RmlUi#238]
First of thanks a lot for your work!

Is there any support for inline svg planned?
eg
```
<svg width="100" height="100">
  <circle cx="50" cy="50" r="40" stroke="green" stroke-width="4" fill="yellow" />
</svg>
```
And, if the support comes, would it be possible to have data bindings inside the svg (for example modifying the radius `r` value)?

**Comment by mikke89** [comment]
Hi, and thank you for the kind words!

We don't have any plans for this unfortunately, currently we only hand over filenames to the SVG plugin. A PR would be welcome to add it though!

Having data bindings with inline SVG is a pretty cool idea I must say, although I suspect that one will be quite tricky since we don't parse any SVG ourselves.

**Comment by vanlueckn** [comment]
Has this feature been integrated into RMLUi in the meantime?

**Comment by mikke89** [comment]
Nope, no one has picked up this work.
