### ISSUE TITLE
drag: clone doesn't work if the element was created by code

### ISSUE THREAD

**Issue by martonp96** [mikke89/RmlUi#264]
Hello,

Version: latest release (4.3)

This is the RML i used for the test: https://pastebin.com/sQsnLEGP

Code:
```
    auto leftBody = document->QuerySelector(".container-body-left > .flex-body");
    auto dragElem = document->CreateElement("div");
    dragElem->SetClass("flex-item", true);
    leftBody->AppendChild(std::move(dragElem)); 
```

You can see on the video that the left box which was there in the RML works, while the new i added on the right side doesn't work:

https://s10.gifyu.com/images/ezgif.com-gif-makeraf65bc5247eda091.gif

In the inspector both elements are the same, and the events are working correctly on both.

**Comment by mikke89** [comment]
Hi, and thanks for the detailed report.

Tested it and I'm able to reproduce it. Looks like the element is actually cloned, it just doesn't get the classes that have been programmatically set applied to the clone. This again is because `Element::SetClass` doesn't actually modify the `class` attribute. I'll think a bit more about a proper way to solve this. Thanks for reporting!

**Comment by mikke89** [comment]
Hopefully this fixes the issue for you. This issue is very much analogous to #218 and was fixed in the same manner.
