### ISSUE TITLE
StyleSheetSpecification instance in nullptr when dynamicaly linking in engine

### ISSUE THREAD

**Issue by SamCZ** [mikke89/RmlUi#272]
Hi, I have game where I use my engine, to this time I was just using static linking, but I wanted to speed up compile of the game, so I just added support to compile dynamically, but then I get a crash

![image](https://user-images.githubusercontent.com/5303066/152166272-4c878c6e-7b13-4f2b-a7a6-36488aeaa68a.png)
![image](https://user-images.githubusercontent.com/5303066/152166301-381d4d24-22aa-44f0-8d3d-1f3c629c4a17.png)

even when `bool StyleSheetSpecification::Initialise()` is called it still crash.

When I debug it the static variable `instance` is NULL.
If I switch to static it works again.

**Comment by mikke89** [comment]
Hi! It's very hard to say what the issue is based on this information alone. If it crashes on something trivial during initialization it is an indication on some issues with the build setup.

Generally, make sure all your compilation flags are the same for the different libraries, and that your std-library is also dynamically linked. Also make sure that you are linking the correct libraries, that you don't have versioning mismatch, ie. the compiled library not matching the included library headers.

**Comment by SamCZ** [comment]
It is loading document without problem, it crashes just when it tries to read rcss. So if it would be bad build setup I think that it would crash at the initialization of the library

**Comment by SamCZ** [comment]
I was just stepping through the Core.cpp Initialize and found out that when `StyleSheetSpecification::Initialise()` goes out of scope the `static StyleSheetSpecification* instance = nullptr;` is set to NULL, idk why.

**Comment by SamCZ** [comment]
ok I found a fix, I was static linking RmlUi to my dynamic lib and I just change it to link both dynamic and it works now.

**Comment by mikke89** [comment]
I see, I'm glad you have it working :)
