### ISSUE TITLE
font-effect transitions

### ISSUE THREAD

**Issue by bugproof** [mikke89/RmlUi#281]
Transitions don't work with `font-effect`

`[Warning] - Property value 'shadow( 2px 2px black )' is not a valid target for interpolation.`

https://tobiasahlin.com/blog/how-to-animate-box-shadow/

it'd be much more flexible if those effects could be applied to other elements as well not only fonts.

**Comment by mikke89** [comment]
Although it would be nice with animation support for font effects, I must consider them out of scope right now.

There would be performance issues to consider since font effects are rendered on the CPU, and they're not really architectured to be re-rendered each frame. This would require investing work into the font engine to handle fonts that are changing more often, which it isn't really suited for right now. And we would also have to consider moving some of this work to the GPU, which would require new API.

**Comment by bugproof** [comment]
perhaps https://github.com/hypernewbie/VEFontCache or https://sluglibrary.com/

**Comment by mikke89** [comment]
We don't have any plans to add animation or transition support directly to font-effects. However, look out for filter animation support in the future, which should be able to do many of the same types of effects - including drop-shadows. This is already working in the `filter` branch, and is targeted for RmlUi 6.0.
