### ISSUE TITLE
Issues with sample invaders: EventInstancer

### ISSUE THREAD

**Issue by TheParadox** [mikke89/RmlUi#298]
Greetings, 
I am trying to use the Invaders sample and SFML example to integrate RmlUi into my application - nearly there. However, I have run into an issue with the EventInstancer.
First, yes - I have copied all the code from the Sample and SFML integration, cause it works?

Well until the EventInstancer:
In the main.cpp on lines 131, 132 it has these two lines to create it:
`
	EventInstancer eventListenerInstance;
	Rml::Factory::RegisterEventInstancer(&eventListenerInstance);
`

Well the error its giving me is:
`Severity	Code	Description	Project	File	Line	Suppression State
Error	C2664	'void Rml::Factory::RegisterEventInstancer(Rml::EventInstancer *)': cannot convert argument 1 from 'EventInstancer *' to 'Rml::EventInstancer *'	PROJECTNAME ------------\src\Application.cpp	27`

I copied the EventInstancer code but its still giving the error. I mean if you look at the definition and declaration for Rml::Factory::RegisterEventInstancer -- it takes Rml::EventInstancer NOT a Rml::EventListenerInstancer which is the abstract class used in the sample:

``
#include <RmlUi/Core/EventListenerInstancer.h>

/**
	@author Peter Curry
 */

class EventInstancer : public Rml::EventListenerInstancer {
//class EventInstancer : public Rml::EventInstancer { <- some functions are not defined BUT the Instancer takes it as a param.
public:
	EventInstancer();
	virtual ~EventInstancer();

	// Instances a new event handle for Invaders.
	Rml::EventListener* InstanceEventListener(const Rml::String& value, Rml::Element* element) override;

};
'

Has the code be updated and the samples not?

Thanks

**Comment by mikke89** [comment]
Hi there.

Yeah, the so called `EventInstancer` in the invader sample is badly named. It should have been called something like `InvaderEventListenerInstancer`, because it really is a `Rml::EventListenerInstancer` as you can see it is derived from.

To register it with the factory, you need to use `Rml::Factory::RegisterEventListenerInstancer`, and **not** `Rml::Factory::RegisterEventInstancer`.

By the way, I did find some issues while refactoring the SFML sample for the backends that will be introduced in RmlUi 5.0. You might want to take a look at the SFML backend here: https://github.com/mikke89/RmlUi/tree/backends/Backends
Keep in mind though that the backends are still a work in progress.

**Comment by mikke89** [comment]
Great! Yeah, that sounds like a good approach, having the samples work in your own setup is a good start.
