### ISSUE TITLE
LoadDocumentFromMemory is useless

### ISSUE THREAD

**Issue by xland** [mikke89/RmlUi#306]
OS:Windows 10
master branch
Code:
```c++
std::string docStr = R"(<rml>
	<head>
		<title>Demo</title>
		<link type="text/template" href="window.rml" />
		<style>
			body
			{
				width: 300dp;
				height: 225dp;
				
				margin: auto;
			}			
			div#title_bar div#icon
			{
				display: none;
			}
			
			div#content
			{
				text-align: left;
			}
		</style>
	</head>
	<body template="window">
		This is a sample.
	</body>
</rml>)";
	Rml::ElementDocument* document = context->LoadDocumentFromMemory(docStr);
```
Error:
The read access permission conflicts

![image](https://user-images.githubusercontent.com/2980915/168021385-325c6a68-f84a-4c22-908d-0b9da36848ab.png)

**Comment by mikke89** [comment]
Thanks for reporting.

This error message doesn't tell us a whole lot, at least we need a stack trace to understand what is going on.

With that said, I suspect that you need to provide a source path to `LoadDocumentFromMemory`, otherwise there might be trouble when trying to resolve the relative path to `window.rml` referenced in the RML source.

**Comment by xland** [comment]
Yes, Thanks
I forgot the `source_url` parameter of the `LoadDocumentFromMemory`

> Should this parameter be a parameter with a default value?

Some info for other developers
The `source_url` parameter value should be:
`D://project//x64//Debug//assets//`
Not
`D:\\project\\x64\\Debug\\assets\\`
And not
`D:/project/x64/Debug/assets/`
