### ISSUE TITLE
Owner Document/dimensions_scale on dynamically created <img> Elements

### ISSUE THREAD

**Issue by kim8823** [mikke89/RmlUi#310]
My app uses density independent pixel ratio to support high-density displays, I'm using the latest release, 4.3.
I'm loading a document and clone a subtree that contains images. These cloned images come out too small when using a dp ratio > 1 because they don't have an owner document when `LoadTexture` runs, can't find a context and default to a dp ratio of 1. The same happens with manually created elements (`Rml::Factory::InstanceElement` in my case), although I haven't looked closely at those yet.

The cloning happens right after loading the document, `InstanceElement` is called in an instancer for custom elements that are loaded with the document, before any `Update` calls. When they get to `LoadTexture` they should already be firmly attached to the document, so I'm not sure what the actual issue is.

**Comment by mikke89** [comment]
Hey, thanks for reporting.

I had some trouble reproducing it initially, since cloning an image element directly works fine. But the key thing here as you mention is to clone a wrapper element with descendant images. Then I can see that the dp-scaling is not applied to the image elements.

I'll take a closer look and try to figure out a solution.

**Comment by mikke89** [comment]
Could you test these changes and let me know if they solve the issue?

**Comment by kim8823** [comment]
Works great, thank you!

**Comment by mikke89** [comment]
Great, no problem!
