### ISSUE TITLE
CJK Input delay so much

### ISSUE THREAD

**Issue by xland** [mikke89/RmlUi#311]
I record a video to show this issue.
Does `WM_KEYDOWN` or `WM_CHAR` message processor do too much work?
It seems that the video should be downloaded to play.

https://user-images.githubusercontent.com/2980915/168450778-25645346-b748-4cae-86ce-278606e40ed8.mp4

**Comment by mikke89** [comment]
Thanks for reporting. I think I may have found the culprit.

I haven't had any experience with IME overlays previously, but I tried to install a CJK keyboard for testing, and yes I can confirm that the input is very slow.

I tested this on the `backends` branch so we can easily switch backends, there I found that everything is smooth on the GLFW backend, and slow on the Win32 backend. As an aside, I didn't get any input on the SDL backend, not sure what's going on there but I'll take a closer look. In any case, this pointed to the Win32 backend as the culprit.

Eventually I found that `PeekMessage` was called at most once a frame, replacing this with a while-loop seems to solve the issue for me. I'm guessing there are more Windows messages generated with CJK input, and because the messages were tied to the frame rate the input becomes very slow.

Can you test the change I made in the `backends` branch?

**Comment by xland** [comment]
I've tested it.
It's great. 
No delay any more.

**Comment by mikke89** [comment]
That's good to hear!
