### ISSUE TITLE
Conditionally call event functions in data-event- expressions

### ISSUE THREAD

**Issue by eugeneko** [mikke89/RmlUi#347]
It would be useful to have at least some primitive syntax for this. E.g. `expr ?? event(args)`.
Should be very easy to parse because `??` never happens outside of the strings.
Another option is true ternary operator, but it's probably harder to parse.

**Comment by mikke89** [comment]
Thanks for the suggestion. Can I ask, what is the use case for this?

While I can see it being useful, I'm trying to avoid making the data-bindings into a full scripting language. And I'm worried about the potential for feature creep here. I mean, next we want not only an `if`-conditional, but also an `else`, and then `else if`, and then multiple statements, and then inline variables. And before you know it suddenly we'll have re-invented javascript.

Generally I want to keep data bindings about presentation and not behavior.

**Comment by eugeneko** [comment]
This is a good reply and it took me some time to formulate an answer.

You see, I would like to keep things in one place. If I have UI-specific variable which corresponds to submenu being open, and I never use it in C++ code for anything else, I would prefer to manipulate it in one place, i.e. in rml file.

This is my specific use case, cut for clarity:
```
<navigable group="game_to_load_group" data-for="saved_game_text : saved_games" class="game-to-load-button-controller"
    data-event-pressed="game_to_load=saved_game_text; ev.is_keyboard ?? on_load_game(); ev.is_keyboard ?? navigable_pop()"
    data-event-dblclick="game_to_load=saved_game_text; on_load_game(); navigable_pop()">
    <input type="button" class="navigable-button list-button" data-rml="saved_game_text"></input>
</navigable>
```

I have an event `pressed` which is generally used "as-is" but in this specific case I would like to have slightly different behavior for mouse and keyboard.
If I move the checks into functions, I will obscure intended behavior. It will be much harder to tell that these things happen only under specific conditions.

With conditions I will be able to use C++ for substantial behaviors and Rml for simple UI behaviors without mixing them.

**Comment by eugeneko** [comment]
I am tempted to just use transform functions instead of events and do some hacks to make them work.
I guess that's part of the reason why I am asking for this suggestion: *RmlUI already does everything I want*, except in different place.

**Comment by eugeneko** [comment]
Update: I did my homework and found out that RmlUI doesn't do lazy ternary ops... So I guess my suggestion is only syntaxically similar, my hack will not work, and I don't know how to implement it in current RmlUI workflow.

**Comment by mikke89** [comment]
Thanks for the example. I appreciate that you understand the sentiment of my previous comment. It is hard to draw a definitive line between convenience and feature creep, however, I think conditionals in particular is a pretty major step in the direction of a scripting language, which is why I am reluctant. Perhaps what you really want is a scripting language such as the Lua plugin.

I want to emphasize that *convenience* as an argument does not have a stop condition, and can be used to justify pretty much any new feature. That is why it must be carefully considered and we must look for alternatives first.

With those considerations, let's examine your suggested example:
`ev.is_keyboard ?? on_load_game(); ev.is_keyboard ?? navigable_pop()`
I belive this can already be solved satisfactory:

- My first suggestion would be to create a C++ event function to handle this. 
`on_navigation_press(ev.is_keyboard)`
I think such a function fits nicely with the scope of other similar functions such as navigable_pop(), perhaps a bit inconvenient but no show-stopper, it can be done in a couple of lines of C++.

- Alternatively, if you want more of a scripted approach, you could create a general delegator function:
`my_delegator(ev.is_keyboard ? 'on_load_game' : 'navigable_pop')`
You could in principle infinitely nest this with conditionals if you so desire.

In my opinion, each of these approaches are good enough that introducing new syntax and language features is not justified.

By the way, transform functions are not intended to be used like that. Generally there is no control over when they are executed, they are assumed to give the same output from the same input, and not have side-effects. Also, I don't understand why you would want use them in this context instead of event functions.

**Comment by eugeneko** [comment]
> My first suggestion would be to create a C++ event function to handle this.

I basically do it as workaround now: all my functions have first parameter reserved for invoke condition.
Which is... good enough as workaround, but I am still mulling over this subject: whether there's anything that RmlUI can do to make this use case simpler.

> By the way, transform functions are not intended to be used like that

Yeah, I know, I wrote it in the latest message. It just took me some time to understand the internal mechanisms of RmlUI.

**Comment by mikke89** [comment]
Appreciate the feedback. I'm closing this for now as I don't find the cost-benefit ratio for this new syntax good enough, and there are decent workarounds. Maybe we'll revisit it in the future.
