### ISSUE TITLE
Support for more languages in text-transform

### ISSUE THREAD

**Issue by zziger** [mikke89/RmlUi#424]
Currently when `text-transform: uppercase`, neither cyrillic nor some extended latin alphabets are supported.

String `test тест ąęćł` looks like this 
![image](https://user-images.githubusercontent.com/27638710/222890592-faec9dbe-805e-4b55-829d-4856fe7906c2.png)
when `text-transform: uppercase` is applied, even though all the characters has their uppercase versions (`TEST ТЕСТ ĄĘĆŁ`)

**Comment by mikke89** [comment]
Hey, and welcome. You're right, currently we only do basic ASCII case conversion.

It would be a nice-to-have feature, but the Unicode case mappings are also quite big and complicated. The work-around is also straightforward: just do the conversion on the client side and then set it on the document.

Since we aim to be lightweight and not add bloat for those that don't need it, I am reluctant to add these tables into the core library. However, I think it would be a natural part of making #211 happen, with an optional library that could handle these kinds of Unicode mappings. In the meantime, you will have to do the conversions yourself.
