### ISSUE TITLE
Minimum GLFW + GLAD + RMLui setup

### ISSUE THREAD

**Issue by Intervel** [mikke89/RmlUi#469]
hello! im still new in c++ programming, i came from web programming ;)  

would anyone help me setup the project with GLFW + GLAD + RMLUI?

i already make the window, but didnt know how to setup RMLui?

please help? im still new :(

![Intervel Game - Microsoft Visual Studio 6_3_2023 5_47_27 PM](https://github.com/mikke89/RmlUi/assets/86478025/793f84a6-479f-4ca6-8131-be996ba28ac9)

here is the file :

https://file.io/rFrq1cFc75C8

**Comment by mikke89** [comment]
Hey there!

Did you take a look at the documentation? It contains quite detailed building and integration instructions: https://mikke89.github.io/RmlUiDoc/pages/cpp_manual.html

Make sure to also take a look at the included backends, as there is already support for GLFW there.

**Comment by Intervel** [comment]
thanks mikke89 for replying! :)
 
i include the backends like you said. then.

![Intervel Game - Microsoft Visual Studio 6_4_2023 12_35_25 PM](https://github.com/mikke89/RmlUi/assets/86478025/447577a8-c3ae-4fa8-a4ce-12072eee0dad)

i dont know what happen? so many error from opengl glad ?

https://github.com/Dav1dde/glad

minimum project :

https://file.io/DCidrp8NGEBg

**Comment by mikke89** [comment]
No worries :) 

Looks like the function definitions for glad are included multiple times. Are you already including the implementation for glad somewhere in your project? Our GL3 renderer by default pulls in those definitions itself. Look for the `GLAD_GL_IMPLEMENTATION` definition, it should only appear in one file. Also, the "RmlUi_Include_GL3.h" file is itself glad, so make sure you don't mix it with another version of glad in case you already added it. I hope this can help you on the right track.

**Comment by Intervel** [comment]
thanks for the reply! you are right! i already included glad, now i remove it.
then fix the glad issues, but errors still remains :

![Intervel Game - Microsoft Visual Studio 6_4_2023 8_06_19 PM](https://github.com/mikke89/RmlUi/assets/86478025/4b10fa31-4efe-4f6a-be1c-2d5913021ded)

not sure what that means?

**Comment by mikke89** [comment]
Glad to hear it worked. The error means that there is no main function, every C++ application needs one as a starting point. You can take a look at our samples to see how it is done there. I would also recommend to check out some more general C++-oriented resources, a great starting point is "A Tour of C++" by Bjarne Stroustrup.

**Comment by Intervel** [comment]
![Test - Microsoft Visual Studio 6_8_2023 11_27_38 AM](https://github.com/mikke89/RmlUi/assets/86478025/01078727-7a53-45a6-9a88-47bdc75ac213)

i added main.cpp. errors still occure?

minimum project :
https://file.io/YPHu65rz7aWH

**Comment by hobyst** [comment]
@Intervel The error that you are experiencing is the "unresolved external symbol" error. In terms of web front-end development it would be the equivalent to say "a definition for the function you are trying to call hasn't been found".

In interpreted programming languages like JavaScript, using libraries is a matter of including the necessary source files so they are available to the browser, but in natively-compiled languages like C and C++ things get trickier. When compiling source code files on their own and generating native code object files (`.o`), all the compiler needs is the function declarations (similar to how functions, classes and others are `import`ed in JavaScript and Python) so that the compiler knows you aren't throwing random function calls. These function declarations are usually done by including header files in the source code file (`#include ...`).

The association of the declared functions to their actual definition and therefore the actual code that defines their behavior is done by the linker when building executables (`.exe` in Windows) and library files (`.dll` for shared/dynamic libraries and `.lib` for static libraries on Windows). The difference between static and shared libraries is that static libraries get embedded into the file they are being linked to while shared libraries are meant to remain standalone to the code that uses them. The linker is in charge of revising all declared symbols by looking for their definitions in all the code object files and the library files you link against and therefore it needs to know which libraries you are using so that it can link their code to your application as well as generating the necessary metadata for the operating system and even linkers to utilize the library or executable file it generates.

When using the linker directly through the terminal you can specify which code object files conform your executable or library and which libraries you want to link against. However when using build systems you need to tell the build system which libraries you are linking against so that it can pass that information to the linker. Assuming that you are using the build from the releases page on GitHub, you can follow [these steps](https://mikke89.github.io/RmlUiDoc/pages/cpp_manual/integrating.html#visual-studio) to configure the Visual Studio solution to properly link against RmlUi. Doing this should solve all the `LNK2019` errors you are experiencing related to RmlUi.

As a note for the future: That `__declspec()` thing that appears will become rather common for you as you get used to C/C++ development on Windows. Dynamically-linked libraries (`.dll`) have a table of symbols the linker can read in order to find symbols to link against just like other shared object file formats used on other operating systems. However, one of the quirks about Windows is that by default no public symbols will be added to the table so developers have to explicitly add them by either writing a metadata `.def` file or marking the functions using `__declspec(dllexport)` to export the symbols and tell the consumers to use  `__declspec(dllimport)` to import them into their library/executable. This, along with the fact that using this breaks static linking with the library, makes developers adapt their code and headers so that consumers have an easier time integrating their libraries into their projects. In the case of RmlUi, the pre-processor definition `RMLUI_STATIC_LIB` is used to disable the use of `__declspec(dllimport)`/`__declspec(dllexport)` and allow consumers to use RmlUi library as a statically-linked library. More info about how dynamically-linked libraries work on Windows:

- [Create C/C++ DLLs in Visual Studio](https://learn.microsoft.com/en-us/cpp/build/dlls-in-visual-cpp)
- [Link an executable to a DLL](https://learn.microsoft.com/en-us/cpp/build/linking-an-executable-to-a-dll)
- [Importing and exporting](https://learn.microsoft.com/en-us/cpp/build/importing-and-exporting)
