### ISSUE TITLE
Checkbox event and status update order

### ISSUE THREAD

**Issue by YTN0** [mikke89/RmlUi#482]
I added an event handler to a checkbox. I tried both the onclick and onchange, and the behavior seems to be the same. I basically want to perform some processing when the checkbox is clicked based on the current state of the check (true / false). 

However, the problem seems to be that the checkbox state isn't updated when the checkbox event has fired i.e. if the checkbox is unchecked and I click it, during the event handler, checking the current checkbox state returns "false" instead of "true" (the current state based on the click).

**Comment by mikke89** [comment]
Hm, I think the behavior is supposed to be as you expect. How do you determine the checkbox state?

**Comment by YTN0** [comment]
I am just reading the current value of the checkbox during the event handler. I have however switched to a different solution for handling this so have not dug into this anymore.

**Comment by mikke89** [comment]
Alright, we can close this then.

**Comment by exjam** [comment]
FWIW I also found this behavior very surprising.

Essentially I am trying to be notified in my code when the user changes the value of a checkbox. Though I would also assume this behaviour extends to all input types due to it being a problem with the order of event listeners.

What I expected to work was:
`<input type="checkbox" data-checked="thing" onchange="thing_changed" />`

But the event listener for onchange is called before the data model's event listener, and thus when you are handling the change event the data model variable is on the old value and not the new value.

If you use data-event-change="thing_changed_fn()" then the model is updated before the function is called, however the function will also be called when the model is changed from code and not only from user input.

If you use data-event-click (in an attempt to avoid the data-event-change being called via code-driven changes of the model) then again the data model does not have the new value in during the callback.

I can think of many different workarounds for this issue, but I am unsure of what the idiomatic solution for reacting to data model value changes from code is supposed to be.

**Comment by mikke89** [comment]
If you want to check the value after it has changed, to me it makes a lot more sense to actually use the `change` event. The `click` event is not really guaranteed to result in a change. Ideally though, we would only emit change when initiated by a user.

I don't see that there really is some correct way order the execution of events in terms of `on...` vs `data-event-...`. Having a dependency on this order at all sounds a bit fragile to me, I'd try to avoid that.

In terms of the `click` event and input value/checked status: To me, the current behavior makes sense, that click event runs first and leads to a value change during its default action, which runs after user actions. This allows users to prevent the default action so that its value/checked status does not change.

I spent some time studying browser implementations, [see the fiddle here](https://jsfiddle.net/kmouse/gbpr5nzf/). Actually I see that they use the new value of the target element during the `click` handler. What's strange about this is that even when we call `event.preventDefault()`, it still returns the new value that is never actually set. So they must be doing some kind of "magic" value decoration. To me, this sounds complicated and also quite surprising, not really a way I want to go down.

But all in all, I believe the most actionable thing we can do in the library is to make `change` events only respond to user input (and also, our `change` event is really more like HTML `input` event). That will probably require some larger changes, and perhaps we want to keep another way to listen to any change, including from the API.

**Comment by exjam** [comment]
Actually I just realised another quirk here with data-event-change.

If you use data-checked with data-event-change, then the data-event-change callback is executed after data-checked, so you have the new value.

If you use data-value with data-event-change, then the data-event-change callback is executed before data-value, so you have the old value

I took a look in ApplyDataViewsControllersInternal and it seems they're applied in whatever order element->GetAttributes() returns. Would it better to apply these in a well defined order such that data-event-change is always called after data-value / data-checked? Or should it be documented that it is undefined behaviour to try read the data model value in the data-event-change callback and instead we should be using the event parameters to get the new value?

**Comment by mikke89** [comment]
Yeah, I think it would make sense to define this order. We already have a defined update order for data-views in terms of evaluating the expressions. However, as you've noticed, we don't have one for the order their event listeners are attached. I think it would make sense to add that.

I guess we should also consider other events than just `change`. Are there anyone that we would want to have executed before e.g. `data-value` and `data-checked`, or is all we need to do, is to attach `data-event-...` last?

I think it would be more suitable to continue this discussion in a new issue.
