### ISSUE TITLE
Preventing the interface from freezing when loading textures.

### ISSUE THREAD

**Issue by xharen** [mikke89/RmlUi#492]
Hello, 
I wrote my custom code for the "LoadTexture" function that will run in an independent thread to prevent the interface from freezing while loading images, but since this thread runs independently, the "texture_handle" variable defined in the parameter of the function changes late and the "CompileGeometry" function is called because the function returns True before the process in the thread is finished and the image does not appear because it compiles the "texture_handle" variable as empty and gives a "RenderCompiledGeometry" error. How do I solve this problem, do I need to make a change in the source code of RmlUi? Or do I need to manually call the "CompileGeometry" function in the thread? If so, how can I call it because I need to define variables like "vertices, num_vertices, indices, num_indices" as parameters. If this method is wrong, do you have a better method for what I am trying to do? **_When I call Therad as a dependent, the interface freezes until the images are loaded and finally the images render properly (when calling a thread with .join)._**

My platform is "GLFW", Renderer is "OpenGL 3"

The code I wrote for the LoadTexture function:
```c++
bool RenderInterface_GL3::LoadTexture(Rml::TextureHandle& texture_handle, Rml::Vector2i& texture_dimensions, const Rml::String& source)
{
	std::thread([&]() {
		int image_width, image_height;
		unsigned char* image_data = NULL;

		FILE* file = fopen(source.c_str(), "rb");
		if (!file)
		{
			printf("The file could not be loaded!\n");
			return false;
		}

		image_data = stbi_load_from_file(file, &image_width, &image_height, NULL, 0);
		fclose(file);

		if (image_data == NULL)
		{
			printf("Image data is broken!\n");
			return false;
		}

		texture_dimensions.x = image_width;
		texture_dimensions.y = image_height;

		wglMakeCurrent(GUI::mainThread_hdc, GUI::newThread_hglrc);
		GenerateTexture(texture_handle, image_data, texture_dimensions);
		wglMakeCurrent(nullptr, nullptr);
	}).detach();

	return true;
}
```

Best Regards.

**Comment by mikke89** [comment]
Hey, and welcome.

I understand it as a desire to lazy-load the textures so that they don't block rendering. The code you posted will generally not work, and possibly lead to a crash or worse, because the output parameters of that function (references) are not guaranteed to live longer than the function call.

Instead, I'd suggest something else: Generate a new unique identifier that you set the texture handle to. Start loading your texture on another thread, and use the generated identifier as a local reference somehow to your thread and its result (e.g. through a lookup map or as a pointer to a data struct). Later, during the call to RenderGeometry/RenderCompiledGeometry, lookup that texture handle, and check if it has finished loading. If it hasn't, render e.g. a white texture as a placeholder. When it has finished loading, just render the correct one instead.

One issue here is that the dimensions of the image are needed immediately (this can affect layouting among other things). So this cannot be lazy-loaded, however, at least stbi has `stbi_info_from_memory` to get the image dimensions without decoding it, which should hopefully be fast enough.

Finally, I'd generally recommend to keep most of your textures in memory, so you don't get hiccups like these. You can retrieve all the currently referenced textures using `Rml::GetTextureSourceList()` after loading your documents, which might be helpful.

By the way, constructing a new thread is a heavy operation, as an optimization you might want to use a thread pool instead.

**Comment by xharen** [comment]
Thank you for your answer. Can you explain more clearly step by step?

**Comment by mikke89** [comment]
Sure, I think it is easier to express the idea in code. Here is a very rough, untested example. It is only for conveying the idea, you will have to fill in the details yourself.

```cpp
class MyLoadedTexture;

struct MyTexture {
    std::future<MyLoadedTexture> future;
    MyLoadedTexture loaded;
};

bool RenderInterface_GL3::LoadTexture(Rml::TextureHandle& texture_handle, Rml::Vector2i& texture_dimensions, const Rml::String& source)
{
    MyTexture* texture = new MyTexture;
    texture->future = std::async(std::launch::async, []{ 
        MyLoadedTexture texture;
        stbi_load...(&texture, ...);
        return texture;
    });

    stbi_info_from_memory(..., &texture_dimensions.x, ...);
    texture_handle = reinterpret_cast<Rml::TextureHandle>(texture);
    return true;
}

void RenderInterface_GL3::RenderGeometry(Rml::Vertex* vertices, int num_vertices, int* indices, int num_indices, const Rml::TextureHandle handle, const Rml::Vector2f& translation)
{
    MyTexture* texture = reinterpret_cast<MyTexture*>(handle)
    
    if (!texture->loaded && texture->future.wait_for(std::chrono::seconds(0)) == std::future_status::ready)
        texture->loaded = texture->future.get();

    if (texture->loaded)
        glBindTexture(GL_TEXTURE_2D, texture->loaded.GetGLTexture());
    else
        glBindTexture(GL_TEXTURE_2D, some_placeholder_texture.GetGLTexture());

    // Now continue rendering the vertices and indices as normal.
    // ...
}
```

**Comment by xharen** [comment]
I understand your method but there is a problem. When the `LoadTexture` function is called by the library, the Texture is loaded, then the `CompileGeometry` function is called by the library and the `vertices, num_vertices, indices, num_indices` variables in its parameter are provided by the library after the `LoadTexture` function returns true, then the `RenderCompiledGeometry` function is called, in the parameter of this function there is a `CompiledGeometryData handle` variable, this variable is provided after the `CompileGeometry` function is called. Therefore, when the texture is loaded late, I cannot render the texture because I cannot compile it. There is another function called `RenderGeometry`, inside this function the `CompileGeometry` function is called but the `RenderGeometry` function is never called but i think this function is called when the `SetScissorRegion` function is called, but I have no idea about this function, it is like this in the Renderer codes written for OpenGL 3. Correct me if i'm wrong thank you for your support.

**Comment by mikke89** [comment]
I don't really understand the issue you're describing here. The approach would be the same if you're using compiled geometry, just apply the idea to the latter functions instead. I.e. store the texture handle together with the compiled geometry.
