### ISSUE TITLE
Data-For not working for option inside select

### ISSUE THREAD

**Issue by Dakror** [mikke89/RmlUi#509]
Using a data model to generate `<option>`s inside a `<select>` using `<option data-for="it : data">...</option>` causes an error as soon as such an option is selected from the dropdown: "Could not find variable name 'it....' in data model"

That's because when the element gets its RML copied into the `selectvalue` element, the data attribute expressions are copied over, but in this scope the iterator names do not exist as aliases.

My suggested fix would be to add a function in DataModel to allow easily copying aliases from one element to another, to simply re-create the scope in the `selectvalue`. This way the `selectvalue` contents would even still be reactive to data model changes, contrary to other potential approaches of e.g. copying the final properties instead of expressions.

**Comment by mikke89** [comment]
Hm, this seems to work in our databinding sample. I wonder if the issue here is naming the variable `it`? That's a built-in variable name, not sure if it works to set that explicitly. You can replace this expression with `data-for="data"`, or try setting another name for it. If this is the issue, we should probably fix it.

Also there are some known and documented limitations in `select` and `options`, so please check that out. But the intention is that using `data-for` with options should normally work.

**Comment by Dakror** [comment]
I've found out why it works in the samples but not in my instance. The error occurs on a child node inside the option. My concrete code:

```
        <option data-for="it : items">
            <img data-attr-sprite="it.icon.name|placeholder" style="width:16dp;height:16dp;">{{it.name}}
        </option>
```

The error occurs in the attr-sprite expression. The text view works. Results dont change when removing the explicit iterator name or renaming it.

**Comment by mikke89** [comment]
Interesting, do you know why it works for the text view, but not the attribute view?

**Comment by Dakror** [comment]
The reason is apparently pretty straightforward. the text view replaces the RML with the result of the expression, thus loses the original expression during the copy process.

**Comment by mikke89** [comment]
I see, thanks for investigating.

I wonder if that is something to look into as well, so that the actual data views (text views included) are copied over. Currently we have the following limitation [listed in the documentation](https://mikke89.github.io/RmlUiDoc/pages/data_bindings.html):
> The `<select>` element may not always properly reflect changes in the underlying selected or value attributes of its `<option>`s, or the content of the options.

I believe doing this would essentially make the `selectvalue` be updated when the option changes, thus fixing this limitation. That could be quite valuable, but I have no idea how big such a fix would be. And apologies for somewhat side-tracking your issue :)

**Comment by Dakror** [comment]
Apart from text-views, this fix should from what i can see fix all the issues. The problem with text views is that they are not preserved anywhere right now, so even Element#Clone doesn't see the original expression

**Comment by Dakror** [comment]
My suggestion would be to refactor text-views to not modify Element#text but instead a transient textOverride property or something

**Comment by mikke89** [comment]
I'm not sure I exactly follow what you propose. How about something like moving the text view to its parent's attribute during parsing? Thus always preserving it as a value in that attribute and when cloning.

I suggest that we implement your current fix, and then we can spend some more time discussing the other changes and evaluate prototypes, preferably in another issue or pull request.

**Comment by Dakror** [comment]
Okay yeah lets do that then.
