### ISSUE TITLE
Incorrect caretPosition on a first keyboard activation after showing an element

### ISSUE THREAD

**Issue by ShawnCZek** [mikke89/RmlUi#515]
Hey, I have a very specific problem. But as I myself am unsure how to resolve it, I am bringing it to everyone's attention.

In my case scenario, I have a chat window with certain parts hidden by default, such as the input box (the message container is always shown because the player should see new messages). This is very similar to any other game, such as Counter-Strike, Battlefield, Rocket League, etc., and the input box part gets shown once the player wants to type in something.

The problem with having certain elements hidden by default is that once you want to unhide the input box and focus it at the same time, the `caretPosition` argument in `Rml::SystemInterface::ActivateKeyboard()` is invalid. After a little investigation, this is caused by the fact that the offset still needs to be calculated for the elements as they were hidden before. And since the keyboard focus is processed immediately and layouting takes effect only at the end of the frame, it also cannot be corrected earlier.

I am not entirely sure how the library should approach this, as calculating the offset, even for hidden elements, sounds like a possible and unnecessary performance issue. My temporary workaround for this issue is using `visibility: hidden` at the start to let RmlUi do layouting. `display: hidden` is used later on, as just using visibility for the input box causes issues with the input focus, if I remember correctly.

**Comment by mikke89** [comment]
I see, so if I understand correctly, you are unhiding the element, and then manually focusing on it right after. I believe the `ElementDocument::Show` does the right thing: Updating the layout before the autofocus takes place. However, when you do this manually on some element, this doesn't take place automatically.

I would say the proper approach for users in this case is to manually call `ElementDocument::UpdateDocument()` right after showing the element. This should take care of the layout before you call focus. You can read more about this here: https://mikke89.github.io/RmlUiDoc/pages/cpp_manual/documents.html#manually-updating-the-document

I've generally delegated the responsibility of updating the layout in special cases like these to the user, mainly due to the combination of: (1) figuring out exactly what needs to be updated based on which changes can be very complicated in the CSS/HTML model, (2) a correct but widely applied dirtying/re-layouting system can have extreme performance implications, (3) a conservative dirtying/re-layouting system can be faster but will likely have many false negatives (unacceptable) unless serious effort is spent on this.

**Comment by ShawnCZek** [comment]
Thank you for the quick and detailed response. I thought the `UpdateDocument` method was private for some reason. Anyway, replicating the behavior of the `ElementDocument::Show` you brought up fixed the issue for me.

The only problem is that a data variable managed the state. Now, I have to manage the state programmatically as data models are processed by the context and not by the document, of course.

Regarding the library, I understand and quite agree with how things are right now. But then the obvious problem is when some events are queued for the context update, and other events are processed immediately. There is no silver bullet for this, sadly.

**Comment by mikke89** [comment]
Glad to hear you got it working. I agree it's not ideal, but I believe it's the right trade-off for us right now. In the long-term it would be nice to look at handling such cases automatically, but that is still far off.
