### ISSUE TITLE
display: flex doesn't expand the outer containing block

### ISSUE THREAD

**Issue by amlinux** [mikke89/RmlUi#520]
Example that works:
```
		<div style="display: block; background-color: red; padding: 50px;">
			<div style="display: block; background-color: green; width: 100px; height: 100px;">
			</div>
		</div>
```
![image](https://github.com/mikke89/RmlUi/assets/449322/a65398b6-3304-481a-a9e3-1bb909d206fa)

Example that doesn't (note that inner div has "display: flex"):
```
		<div style="display: block; background-color: red; padding: 50px;">
			<div style="display: flex; background-color: green; width: 100px; height: 100px;">
			</div>
		</div>
```
![image](https://github.com/mikke89/RmlUi/assets/449322/cb4ae6ad-eae3-4f91-9fad-30389dabad00)

This behavior is different from CSS where flex containers expand their parents, and I coundn't find any notes about it in the documentation.

I tested this behavior in the 5.1 branch and at head.

**Comment by amlinux** [comment]
Here is the full repro:
```
<rml>
	<body>
		<div style="display: block; background-color: red; padding: 50px;">
			<div style="display: flex; background-color: green; width: 100px; height: 100px;">
			</div>
		</div>
	</body>
</rml>
```

Indeed, if I specify width and height of body as 100%, then it behaves differently:
```
<rml>
	<body style="width: 100%; height: 100%;">
		<div style="display: block; background-color: red; padding: 50px;">
			<div style="display: flex; background-color: green; width: 100px; height: 100px;">
			</div>
		</div>
	</body>
</rml>
```
![image](https://github.com/mikke89/RmlUi/assets/449322/385768ca-5c77-43e1-8d2a-5ed5c3825e16)

**Comment by amlinux** [comment]
I suppose the question is then - why body doesn't expand to fit the outer div?

**Comment by mikke89** [comment]
I see, this is in a shrink-to-fit width context. What's going on here is that body is an absolutely positioned element. When you don't set any width on such elements, they will determine width based on their contents (shrink-to-fit). In RmlUi flexboxes and tables do not currently support shrink-to-fit, which is why it behaves differently from the block display. In this particular case though, their outer width is known, so maybe there is a simple fix to support "easy" cases like this.

The workaround here is simple enough though: Just place the width on the parent div instead of the flex. Or even better, set the width on the body (increase it to include padding). This is generally recommended for performance reasons, unless you really need to rely on fitting to the content.

In your last case, things work out exactly as expected. When you set a specific width on the body, the red div instead follows normal block layout, where blocks fill all available width.

**Comment by mikke89** [comment]
> In this particular case though, their outer width is known, so maybe there is a simple fix to support "easy" cases like this.

Alright, I went ahead and made a fix for this case. Let me know if it works for you :)

**Comment by amlinux** [comment]
Oh wow! Thank you for the detailed explanation and for the fix. Much appreciated!
