### ISSUE TITLE
Vulkan Renderer Win32 Glitching

### ISSUE THREAD

**Issue by DrJedikiah** [mikke89/RmlUi#558]
I've built the latest release and wanted to try it with vulkan backend but there's some weird twitching. I can confirm this doesn't happen with GL2. Tested it with different PCs and GPUs. It doesn't happen if I don't move the cursor (edit: it's due to powersave being true).

There's nothing I specificially modified or added except rml file which I also tested with a sample one and issue still occurs. 

VulkanSDK version: 1.3.268.0

https://github.com/mikke89/RmlUi/assets/12988451/7941a74b-0c5f-4f1e-91b7-9a0d1a6a24c7

**Comment by mikke89** [comment]
It's working fine on my end, can you provide more information? GPU/OS? Which backend are you using? Can you test on another Vulkan backend (i.e. SDL vs Win32)? Have you tried the built-in samples?

Try to run everything in debug mode, and also enable `#define RMLUI_VK_DEBUG`. Ensure validation layers are running, there should be an output message `[Vulkan] CPU validation is enabled`. Finally, you can also test on the latest master, there have been some changes since the latest release.

**Comment by mikke89** [comment]
Alright, thanks for testing different combinations. I've tested more configurations on my end (desktop GTX 1070), and I still can't reproduce it.

If it is working only with validation layers enabled, then it could indicate some subtle illegal or undefined behavior. The validation layers are supposed to catch and report many of these though. Hard to say exactly what the GPU decides to do with that internally, that makes it produce different results.

Could you also test that you are reproducing it on our built-in samples? In case there are some differences on how the renderer is used.

The next step would be to fire up RenderDoc or some other GPU debugger and see what's going on there. I think that's your best bet. Otherwise, try incrementally disabling features and narrowing things down in the renderer until you are able to isolate the issue as much as possible.

**Comment by wh1t3lord** [comment]
@DrJedikiah hello!

Thanks for the feedback I have my laptop with RTX 3060 and I will try to investigate the problem. Sorry if you faced with any troubles but I implemented and tested this backend on Nvidia video cards that lower or equal to gtx 1060. (so I physically couldn't test on modern GPUs sadly) 

For now, it will take some time because I need to finish my work for next Rml release. 

Thanks for the patience and reporting the problem. 

But I need to warn that if issue is not reproducing on 3060 but still persist on your video card that means the problem is in your driver/video card.

**Comment by mikke89** [comment]
@DrJedikiah It would be great with a confirmation that #593 fixes the glitching you experienced.
