### ISSUE TITLE
MSVC Freetype message in `cmake` branch

### ISSUE THREAD

**Issue by snaulX** [mikke89/RmlUi#580]
https://github.com/mikke89/RmlUi/blob/c40d18a4458f43c4cae9b2c70a024b980fea6d93/CMake/Dependencies.cmake#L25
There's check on MSVC without checking on version, but message says that it's because of specific versions usage. So when I tried to use freetype 2.10.0, it gives me warning about 2.11.0 and higher and I was very confused.
So fix the message or check, I don't know why exactly this warning there.

**Comment by mikke89** [comment]
Thanks for reporting. The warning wasn't entirely correct (since it only applies to 2.11.0), and would produce a lot of false positives whenever the version isn't known to us. Thus, I went ahead and removed the warning now: https://github.com/mikke89/RmlUi/commit/d36e0595045a4b67a96eba3c0bc8789036e405f8

Just be aware that the `cmake` branch is still experimental, but it's great to get more testing done on it.
