### ISSUE TITLE
Keyframes animation transform stops working after SetClass(false) on element

### ISSUE THREAD

**Issue by IamFIR3BALL** [mikke89/RmlUi#584]
Hello, i am creating UI for our game using RmlUi. We tried to add horizontal-shake effect on UI appearance(notification), but after first open and close, on next opens no animation is playing. However we fixed it by calling ReloadStyleSheet before SetClass to play animation. I guess there is something with reference counting, because when i tried to debug that in RmlUi internals, in ElementAnimation::UpdateAndGetProperty units was PX and value = 0, but in CSS it was set to percents. It happens only with transform(percent, percent), when i use PX or DP everything works without workaround. Can it be my fault or is it bug in RmlUi?
Sample:

CSS
`@keyframes fadein {
		0%,
		100% {
			transform: translate(-50%, 0%);
		}
		10%,
		30%,
		50%,
		70% {
			transform: translate(-48%, 0%);
		}
		20%,
		40%,
		60% {
			transform: translate(-52%, 0%);
		}
		80% {
			transform: translate(-51%, 0%);
		}
		90% {
			transform: translate(-49%, 0%);
		}
	}
    body
    {
		font-family: Montserrat;
		decorator: image( br_bg_oval_gradient );
    }
	.fadein
	{
		left: 50%;
		transform: translate(-50%, 0%);
		animation: 0.4s linear-in fadein;
	}`

Initialization:
`m_pDocument = g_pRmlUI->GetContext()->LoadDocument("rml/notifications/notifications.rml");
m_pDocument->Hide();`

Showing
`m_pDocument->Show();
m_pDocument->ReloadStyleSheet(); // workaround for "fadein" class(and animation) works
m_pDocument->SetClass("fadein", true);`

Hiding
`m_pDocument->SetClass("fadein", false);
m_pDocument->Hide();`

**Comment by IamFIR3BALL** [comment]
After hours of debugging i realized that after document has been loaded and parsed, it calls Update and tries to add animations which should be played instantly. And if there is transform(percentage) in animation - ResolveWidth will return zero because of zero size main_box. I dont know if this bug, but in HTML/CSS animations declared in classes works automatically after load

**Comment by mikke89** [comment]
Hey, and thanks for reporting.

Right, I think you're onto something with your analysis. I suspect that the animation runs before layout has been performed, and then the percentage resolves against the document which has not been layed-out yet.

Ideally, the interpolation from the animation would only be applied after the layout has been done. However, it's a bit tricky, because the animation itself could in principle affect the layout. This way we could even end up with an infinite cycle of layout updates.

I think for now, it's best to keep the workaround. This will require some careful thinking and design to solve properly.

Note that, this is only an issue if you mix different types of units, like percentages and lengths. If you use only percentages, or only lengths, then interpolation will not depend upon layout.
