### ISSUE TITLE
Change `Element::AddEventListener` to take weak pointers to the event listener

### ISSUE THREAD

**Issue by blaisemccourtney** [mikke89/RmlUi#605]
This suggestion may be a bad idea, or not viable, but just in case it is useful, I am mentioning it either way. I am not certain what the status of RmlUi 6.0 is, like if a breaking change in the interface is acceptable or not at this time RmlUi 6.0 may have been in development for a long time, and I do not know if there are users of it already.

The purpose of the change would be to make lifecycle handling and reasoning easier for users of `Element::AddEventListener()`. The idea would be that the caller of `Element::AddEventListener()` would no longer have to care about when RmlUi is ready to have the `Rml::EventListener` get deleted, but can just delete it (by letting `std::shared_ptr<Rml::EventListener>` get handled normally) when the caller chooses to do so. On RmlUi's side, RmlUi would just have to query `std::weak_ptr::expired()` to see if it is safe to call the event listener when a relevant event happens.

**Comment by mikke89** [comment]
Hey, and thanks for the suggestion.

Lifetime management in C++ can become a complicated topic, so I understand the need to try to simplify things sometimes. With that said, I think replacing what we currently have with a weak pointer is not the right solution. Even with shared ownership, one still needs to think about ownership and lifetimes. Otherwise, in my experience things can easily come back to bite you, in terms of implicit dependencies and destruction order. In my view, an element still having a reference to an event listener that has been destroyed speaks of a lifetime management issue. 

For event listeners specifically, then typically either the element itself should take unique ownership of the event listener. In this case, lifetime management is guaranteed if the listener simply deletes itself ones the listener is released from the element. This is how some of the listeners in our samples are implemented. Otherwise, the user handles the lifetime of the listener, and only "loans" out the object to the element. Then, it is the user's responsibility to ensure that the element is destroyed before the listener. From my experience, this approach is typically only needed from more general listeners that outlive the RmlUi context, in which case lifetime management is unproblematic. I have rarely seen the need for other cases, but if you have a very specific example in mind I am willing to listen. 

I have consider to perhaps simplify this interface by allowing the use of `std::function` callbacks, which would alleviate some cases like this. But of course, one still needs to think about lifetime management in a similar way.

**Comment by blaisemccourtney** [comment]
Thank you for your reply.

I agree about the need for thinking about ownership and lifetimes. One purpose of using `std::weak_ptr` would be to make it clear that it is not the element that owns the listener, but the caller/user that owns the listener, and the caller/user that controls the lifetime of the listener. In the examples you mention, as I understand it, ownership varies (either owned by the element or owned by the user) depending on how the API is used.

For the samples I see, the way it is implemented seem a bit surprising to me. In this code from the Invaders sample,

https://github.com/mikke89/RmlUi/blob/master/Samples/invaders/src/EventListener.cpp#L32-L46

, the listener indeed destroys itself upon the `OnDetach()` method being called, but it also dispatches the event to the custom event management system in the Invaders sample. And that event management system is a singleton that has mutable state, and may be limited to handling one screen at a time.

https://github.com/mikke89/RmlUi/blob/master/Samples/invaders/src/EventManager.cpp#L38-L46

https://github.com/mikke89/RmlUi/blob/master/Samples/invaders/src/EventManager.h#L44-L58

Is it normal or considered best practice to implement such an event management system with a singleton and mutable state? I looked at the sample to get a clearer view of how to approach the lifecycle and ownership of event listeners, but the issue of handling the lifecycle is arguably somewhat sidestepped by the system with a singleton and mutable state. And I could go with such a system, but that approach might have limitations that would not be good for some more complex UIs, I am not certain.

Is there a sample in similar complexity to the Invaders sample, but without a custom event management system that uses a singleton and mutable state?

I do not yet have a good understanding of RmlUi or how to use it well, but one use case I was thinking about (which I would assume might be common) is if you inside some ("outer") element want to add a listener to a nested element, a nested element that might or might not be destroyed while the "outer" element still survives. But maybe the cost of a listener is trivial, and that listener's lifecycle could just be determined to belong to the "outer" element, keeping it around even if unused, and only tear it down upon the "outer" element's destruction despite not being used. Can it be assumed that if an "outer" element is being deleted, that all the nested elements are being deleted, and it is then fine to delete any listeners added to nested elements? As long as the number of listener instances are kept low, then I would guess that this approach might be fine.

**Comment by blaisemccourtney** [comment]
One example I am thinking of is if you have an "outer" or root element, and multiple nested elements, and you add the same event listener to each of those nested elements. You would then have to be careful that you only delete the listener once each of those multiple nested elements have been deleted or have had `OnDetach()` called.

**Comment by blaisemccourtney** [comment]
In this sample code, not library code, just sample code, that includes `AddEventListener()`, https://github.com/mikke89/RmlUi/blob/master/Samples/invaders/src/ElementGame.cpp#L92-L102 , `ElementGame` would probably cause undefined behaviour if `ElementGame` is destroyed and the document is not destroyed and one of the events are triggered. So the sample code is fine as long as care is taken to ensure that `ElementGame` is never destroyed without the document also being destroyed. It all feels a bit fragile to me, but this is a sample, not library code.

The lifetime of the listener itself could in theory be shorter than the element/document it is listening to in this case, even without moving the element. But it is probably fine as long as the element is only destroyed when the document is destroyed.

**Comment by mikke89** [comment]
Alright, there's a lot here. I will first say this. If you truly need shared data with shared ownership between listeners, you are free to pass a shared pointer, or some other reference counted system, into your listeners. Achieving this does not really require library support with weak_ptr.

The samples don't necessarily display best practices, in particular I wouldn't use a singleton with mutable data myself. On the other hand, I often find it useful to tie event listeners to a given document and its lifetime.

When you have a nested set of elements, I would say there are two different useful approaches depending on what is being done:

1. Handle the events in a parent element as they're propagating (during the capture and bubble phase). In this case, lifetime management is trivial with descendants coming and going as they like.
2. Create a new event listener that is unique to a given element and handled by its lifetime. Again, lifetime is quite trivial in that it is uniquely tied to the element. If you really need shared data here, then pass in some shared object at this point.

I agree that the `ElementGame` example you found is problematic since the element does not clean up after itself, leaving references around that are illegal to call after it is destroyed. The fix should be quite easy here though, remove the listeners in the element's `OnChildRemove`.

**Comment by blaisemccourtney** [comment]
Thank you for the answers, that clears things up quite a bit for me. C++ is also a flexible language that offers quite a lot of control, though that also leaves a lot of room to shoot oneself in the foot with. I can see that some of the samples were created by others, as with the comment ```@author Peter Curry``` in 'ElementGame.h' in the sample code that you cleaned up just now. Many other languages than C++ give less control, and also limit which ways one can shoot themselves in the foot - but never excludes the possibility of shooting oneself in the foot. And RmlUi is often used for game programming, where performance and other concerns is typically more important than not having "sharp edges", either way. There has been some talk recently in programming forums in the last couple of months, with C++ and other languages, and the difference between "modern" C++ and older C++, and the White House report a month ago on memory safety and programming languages. But games have different priorities from most other software, and the project I am using RmlUi in is also a game project.

Using something like a `std::weak_ptr` would potentially make it easier for programmers new to the library to avoid shooting themselves in the foot in one way. But programmers would still need to learn the library to avoid shooting themselves in the foot, and `std::weak_ptr` (or some other smart pointer or alternative) might not be a "one size fits all", or even be a good or viable option in the first place.

**Comment by blaisemccourtney** [comment]
You are welcome to close this issue if you want, things are much clearer for me now. I can also close it if you want.

**Comment by mikke89** [comment]
I'm glad to hear we could clarify things.

I am closing this, as I believe it has come to a conclusion. I am considering some improvements to this interface, but don't believe a weak pointer is the right approach here.
