### ISSUE TITLE
Rml::Span doesn't exist when RmlUi is installed from vcpkg which leads to backend compilaton errors

### ISSUE THREAD

**Issue by carljohnson93** [mikke89/RmlUi#623]
Hi! I'm sorry if this is some basic stuff I don't understand, but I'm new to cmake, vcpkg and rmlui, and I don't understand what am I doing wrong. I'm getting compilation errors from renderer source file because it uses to Rml::Span, which apparently has not been declared as the compilation error says. I checked manually in vcpkg/vcpkg_installed/x64-linux/include/RmlUi directory and indeed grep revealed that Rml::Span was nowhere to be found.
Here are the steps I did to try to setup hello world project with RmlUi:
1. make new directory called `hello_rmlui` and `cd` into it
2. run `git clone --depth=1 https://github.com/microsoft/vcpkg` to get vcpkg
3. create `vcpkg.json` file with the contents `{ "dependencies": [ "rmlui", "glfw3" ] }`
4. create `main.cpp` file with the following contents:
```c++
#include <RmlUi/Core.h>
int main() {}
```
5. Manually download `RmlUi_Backend.h`,  `RmlUi_Backend_GLFW_GL3.cpp`,  `RmlUi_Platform_GLFW.cpp`,  `RmlUi_Platform_GLFW.h`,  `RmlUi_Renderer_GL3.cpp` and `RmlUi_Renderer_GL3.h`  from the RmlUi github
6. create `CMakeLists.txt` with the following contents:
```cmake
cmake_minimum_required(VERSION 3.10)

set(CMAKE_TOOLCHAIN_FILE
    "${CMAKE_CURRENT_SOURCE_DIR}/vcpkg/scripts/buildsystems/vcpkg.cmake"
    CACHE STRING "vcpkg toolchain file")

project(hello_rmlui)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED true)

set(CMAKE_EXPORT_COMPILE_COMMANDS true)

add_executable(hello
               main.cpp
               RmlUi_Backend_GLFW_GL3.cpp
               RmlUi_Renderer_GL3.cpp
               RmlUi_Platform_GLFW.cpp
)

find_package(RmlUi CONFIG REQUIRED)
target_link_libraries(hello PRIVATE RmlCore)
``` 
7. Run `cmake -B build -S .`
8. Run `cmake --build build`
Build fails because of the error "Rml::Span has not been declared".

**Comment by mikke89** [comment]
Hey, welcome! And I appreciate the detailed post. It makes it easy for me to see where things are going wrong here.

The issue is that the RmlUi version being fetched from vcpkg is different from the backends that I presume you fetched from the `master` branch. Especially now that we are approaching RmlUi 6.0, they are not compatible.

The solution would be to either download the backends for the version you're using from vcpkg, I believe currently that should be [RmlUi 5.1](https://github.com/mikke89/RmlUi/releases/tag/5.1). Or alternatively, make an overlay port to fetch the latest RmlUi from master.

I wonder if there is something we can do to improve the situation, ideally we should ensure that the backends are always in sync with the library version. Maybe we should install the backends with the vcpkg install. Or I believe there is a way in vcpkg to add optional files as well, maybe that is something we could copy the backends into.

**Comment by carljohnson93** [comment]
Thanks so much, fetching files from 5.1 fixed the issue! Regarding the things you suggested to improve the situation, installing backends with vcpkg install sounds good, but I'm too new to all this so don't really have anything to say further on this, so I'll just close the issue. Thanks for your help!
