### ISSUE TITLE
nth-child(odd) gets confused by data-if (RmlUi 5.1)

### ISSUE THREAD

**Issue by jbatnozic** [mikke89/RmlUi#645]
Hi,

I've been using RmlUi to display a table of players in the game such as this:

```
        <!-- PLAYER TABLE -->
        <div id="player-table-holder" class="window-contents">
            <table data-model="lobby-model">
                <colgroup>
                    <col span="5"/>
                </colgroup>
                <colgroup>
                    <col style="text-align: center;"/>
                    <col/>
                    <col/>
                </colgroup>
                <tbody data-for="player, i : players">
                    <tr data-if="i > 0">
                        <td colspan="8">SLOT {{i}}</td>
                    </tr>
                    <tr data-if="i > 0 && !player.showPending">
                        <td colspan="5">{{player.lockedIn.name}}</td>
                        <td class="button" data-event-click="MoveUp(i)">Move /\</td>
                        <td class="button" data-event-click="MoveDown(i)">Move \/</td>
                        <td class="button">Kick</td>
                    </tr>
                    <tr data-if="i > 0 && player.showPending">
                        <td colspan="5">{{player.lockedIn.name}} &lt;= {{player.pending.name}}</td>
                        <td class="button" data-event-click="MoveUp(i)">Move /\</td>
                        <td class="button" data-event-click="MoveDown(i)">Move \/</td>
                        <td class="button">Kick</td>
                    </tr>
                </tbody>
            </table>
        </div>
```

```
tr:nth-child(odd) {
	background-color: #a1a1a1;
}
```

So the idea is that each odd row (1, 3, 5...) is dark grey and shows a label like "SLOT 2", and each even row (2, 4, 6...) is of the default colour (transparent) and shows info about a player in one of two formats, depending on a flag (hence the `data-if`).

In RmlUi 4.4 this worked perfectly fine. After upgrading to 5.1 (I skipped 5.0), I see that having two `<tr>` elements with opposite conditions confuses the RmlUi engine, with the result being that each odd row is coloured as normal (dark grey), but each even row is coloured either dark grey or transparent depending on which `<tr>` is active at the time. Swapping the order of the `<tr>` elements in the .rml file flips the displayed colours.

**Comment by wh1t3lord** [comment]
Can you provide expected result (reference) from 4.4 and how it looks like in 5.1? I mean Screenshots. 

Thanks. @jbatnozic

**Comment by jbatnozic** [comment]
4.4:
https://github.com/user-attachments/assets/5bf0ca8d-cf56-4999-b14c-6f40767badf8

5.1:
https://github.com/user-attachments/assets/5fea57c3-4b8e-4c18-a762-8fe71e0de7d5

**Comment by mikke89** [comment]
Hey, there!

So, this is actually from an intentional change in 5.0, and the new behavior seems to be correct. So it basically comes down to this line in the changelog:

> Structural selectors are no longer affected by the element's display property, like in CSS.

The implications might not be entirely clear. But basically, for selectors like `:nth-child`, now we only consider the actual tree order of the elements, rather then the displayed order of the elements. It's an important change, I'm sure you can imagine the troubles with having a selector that depends on possibly it's own computed properties. 

Also, keep in mind that `data-if` changes the `display` property of the elements, the elements are still there in the document tree.

In this example table, the solution should be fairly simple though. You can do `:first-child` here to apply the background-color to the "slot" rows, since they are always the first child of their parent `tbody`.

**Comment by jbatnozic** [comment]
Using `:first-child` fixed it.

I mean I thought it would have a simple fix, but I also thought that it was unintended as it used to work. Anyway, I'll close the ticket now. Thanks :)
