### ISSUE TITLE
Textures leaked during shutdown

### ISSUE THREAD

**Issue by hadi-rahimi** [mikke89/RmlUi#647]
Hello,
In the minimal example below, which is a simple animation with two frames,
it loads and runs fine, but on program exit, I get this warning:
`Textures leaked during shutdown. Total: 1  From file: 1  Generated: 0.`
and then there is a null pointer reference on program exit which causes a crash.

```
<rml>
  <head>
    <title>Hello world</title>
    <style>
      body {
        position: absolute;
        width: 500dp;
        height: 300dp;
        margin: auto;
        background-color: white;
      }
      @keyframes anim1 {
        from {
          decorator: image(arror_1.tga);
        }
        to {
          decorator: image(arror_2.tga);
        }
      }
      #div1 {
        display: block;
        position: absolute;
        left: 10dp;
        top: 20dp;
        width: 90dp;
        height: 148dp;
        animation: 1s linear infinite anim1;
      }
    </style>
  </head>
  <body>
    <div id="div1"></div>
  </body>
</rml>
```

After adding `Rml::ReleaseTextures()`, I can see that textures are released and crash is fixed, but the warning is still there.

```
Rml::ReleaseTextures();
Rml::Shutdown();
delete renderInterface;
delete systemInterface;
```

Is this a known issue? I read somewhere you mentioned about a garbage collection problem.

**Comment by mikke89** [comment]
Hello!

Which version / commit of the library are you using? There have been some changes already since that warning. Usually this warning points to some shutdown order issue, either on the library end or on the user end. I tested the document you posted in our `load_document` sample, and I'm not seeing any issues here.

It would be very helpful if you could post a full reproducer, ideally on the latest master branch. I would also suggest just trying the latest commit in any case, as there have been several changes around textures in particular, but be aware that there are some breaking changes though.

**Comment by hadi-rahimi** [comment]
Hello,
The crash can be reproduced in release version `5.1` in `loaddocument` sample. That's the version I use.
But I tested the latest master and it has been fixed.
I will update to the latest master.

Thank you for your help!

**Comment by mikke89** [comment]
Glad to hear, thanks for reporting back!
