### ISSUE TITLE
SVG plugin not working

### ISSUE THREAD

**Issue by std-microblock** [mikke89/RmlUi#687]
![image](https://github.com/user-attachments/assets/1b7dd2c9-06fe-444d-b7c9-42180f80a2f3)
any idea? no error in the log. GL3+GLFW & LunaSVG latest

**Comment by std-microblock** [comment]
well...png neither displays...I guess there must be something wrong with the render backend.

**Comment by mikke89** [comment]
Haven't really seen this. It is working well on my end. I see that I have lunaSVG 2.3.8 installed, so maybe you can try that and see if there are some differences?

As for PNG, note that our built-in renderers only support uncompressed TGA out of the box: https://github.com/mikke89/RmlUi?tab=readme-ov-file#renderers

It is fairly trivial to add your own image types though. See for example how that is done in the [SDL_GL3 backend here](https://github.com/mikke89/RmlUi/blob/14bf5fc85b0e083266061283c351a617aa3e5d86/Backends/RmlUi_Backend_SDL_GL3.cpp#L57).

**Comment by mikke89** [comment]
Also, ensure to check the log output for any messages there.

**Comment by std-microblock** [comment]
> Also, ensure to check the log output for any messages there.

yeah I've checked, no error, no warning

**Comment by std-microblock** [comment]
> Haven't really seen this. It is working well on my end. I see that I have lunaSVG 2.3.8 installed, so maybe you can try that and see if there are some differences?
> 
> As for PNG, note that our built-in renderers only support uncompressed TGA out of the box: https://github.com/mikke89/RmlUi?tab=readme-ov-file#renderers
> 
> It is fairly trivial to add your own image types though. See for example how that is done in the [SDL_GL3 backend here](https://github.com/mikke89/RmlUi/blob/14bf5fc85b0e083266061283c351a617aa3e5d86/Backends/RmlUi_Backend_SDL_GL3.cpp#L57).

uhhm that's so sad
why not consider adding a real png parser, libpng for example, to provide full support for pngs?
also how about webp?

**Comment by wh1t3lord** [comment]
I guess the library tries to be compact by functionality and by output size. So adding libraries means growing in size. If there is a lightweight version of crossplatform universal image handling library I would welcome a such solution. At least there is DirectXTex but it is for windows. (Is it lightweight?) 

Also adding new types of images make harder to maintain library. Remember we don't have only one graphics backend we will have 4 at least. I just suggest to provide image callback for any backend and user can specify on its side what library to use and how the image to process. Indeed a such idea was provided in DX11 backend and I will add in mines.

**Comment by std-microblock** [comment]
I don't really think supporting more picture format would make the library harder to maintain. All the formats should be converted to the raw format before making them a texture, and the process of making a texture from a raw image is the same.

**Comment by std-microblock** [comment]
Yes, we have libvips: https://github.com/libvips/libvips
This.is what chromium used to handle images. Its stability and performance have been proved.

**Comment by std-microblock** [comment]
It also modularized, so the requirements of binary size can be meet. It even supports SVG.
I strongly suggest using it to implement support for more images.

**Comment by mikke89** [comment]
> why not consider adding a real png parser, libpng for example, to provide full support for pngs? also how about webp?

First of all, I want to remind you of the overarching philosophy of our library, from the readme:

> RmlUi aims at being a light-weight and performant library with its own layouting engine and few dependencies. 

Instead of meeting every requirement for every user, we make a highly modular API, where it is easy to extend features and customize the library to their needs. This is a core idea to the library, so that we avoid feature creep and bloat for users that don't need it. This also relates to #450.

Did you take a look at the [example I linked earlier](https://github.com/mikke89/RmlUi/blob/02494caccb3b93d235ce29379c34f7e3c9b34230/Backends/RmlUi_Backend_SDL_GL3.cpp#L57) to add support for other image types? It's literally 50 lines of code.

**Comment by std-microblock** [comment]
> > why not consider adding a real png parser, libpng for example, to provide full support for pngs? also how about webp?
> 
> First of all, I want to remind you of the overarching philosophy of our library, from the readme:
> 
> > RmlUi aims at being a light-weight and performant library with its own layouting engine and few dependencies.
> 
> Instead of meeting every requirement for every user, we make a highly modular API, where it is easy to extend features and customize the library to their needs. This is a core idea to the library, so that we avoid feature creep and bloat for users that don't need it. This also relates to #450.
> 
> Did you take a look at the [example I linked earlier](https://github.com/mikke89/RmlUi/blob/02494caccb3b93d235ce29379c34f7e3c9b34230/Backends/RmlUi_Backend_SDL_GL3.cpp#L57) to add support for other image types? It's literally 50 lines of code.

Yes, it's great. But since we already have SVG support as a plugin, why not other format? It won't even take up extra space if the user do not enable it.

**Comment by mikke89** [comment]
That's fair enough. Our plugin system doesn't currently fit well for image types though, since images are loaded in the backend. So we would possibly have to devise some new API. Which also might be a bit confusing considering that we already have an existing API through the render interface.

I'll keep this in mind for the future, but for now this is not a high enough priority to be worked on, if this is something we want at all. Especially considering that the solution requires I would say relatively low effort from users, and we already serve examples on how to do it.

**Comment by mikke89** [comment]
I recently tested with LunaSVG 3.0.0, and I got the same output. It turns out there is a bug in that version, which was later fixed here: 2246b6a171bb4e64a20d793861de8f44862fed53

So if you use LunaSVG 3.0.0, please upgrade to a commit that includes the above fix, or wait for a new release.

I've pushed some changes to log some warnings when the SVG cannot be rendered. With that, I consider this issue resolved.

**Comment by std-microblock** [comment]
Okay, thanks!
